### ISSUE TITLE
DPL-665 - Bioscan - RESEARCH how to access the XP tube source barcode from the Pacbio::Run object

### ISSUE THREAD

**Issue by andrewsparkes** [sanger-archive/traction#26]
**User story**
As PSD we need to understand how the Limber XP tube barcode reference will be passed through into Traction and be accessible on the run. This reference will let the user connect the run to the mBrave file generated from the XP tube sample metadata.

**Who are the primary contacts for this story**
PSD

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] understand how the source tube barcode will be passed through the export process into Limber and how it can be displayed to the user at the run stage in Traction
- [ ] write up any required stories

**Dependencies**
This story is blocked by the following dependencies:
- None

References
This story has a non-blocking relationship with:
- DPL-662, 663, and 666

**Additional context**
The Limber tube being exported to Traction may contain up to 9216 samples. We only need 1 sample for Traction as de-plexing is done via mBrave software later. The export message should include the XP tube barcode (and maybe UUID). In Traction that 'source' can possibly be stored in the traction object(s) created there, so that it is accessible when we display the run rows. The user can then relate that source barcode to the mBrave file that should have been created when the Limber export into Traction was performed (the filename could include the barcode).

**Comment by harrietc52** [comment]
Deprioritised in [DPL-694](https://github.com/sanger/General-Backlog-Items/issues/280)
